#!/usr/bin/env python3
"""Basics of async module."""


from asyncio import sleep
from random import uniform


async def wait_random(max_delay: int = 10) -> float:
    """
    Wait for a random delay.

    args:
        max_delay (int): upper limit of the delay
    Returns:
        the random delay generated by the uniform function

    """
    random_delay: float = uniform(0, max_delay)
    await sleep(random_delay)
    return random_delay
